function apply(){
				document.frm.sub.disabled=true;
				document.frm.submit.disabled=true;
				document.frm.submit2.disabled=true;
				if(document.frm.check1.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				if(document.frm.check2.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				if(document.frm.check3.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				if(document.frm.check4.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				if(document.frm.check5.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				if(document.frm.check6.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				if(document.frm.check7.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				if(document.frm.check8.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				if(document.frm.check9.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				if(document.frm.check10.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				if(document.frm.check11.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				if(document.frm.check12.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				if(document.frm.check13.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				if(document.frm.check14.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				if(document.frm.check15.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				if(document.frm.check16.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				if(document.frm.check17.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				if(document.frm.check18.checked==true){
					document.frm.sub.disabled=false;
					document.frm.submit.disabled=false;
					document.frm.submit2.disabled=false;
				}
				
				if(document.frm.check1.checked==false){
					document.frm.sub.enabled=false;
					document.frm.submit.enabled=false;
					document.frm.submit2.enabled=false;
				}	
		}

function apply1(){
	document.frm.submit.disabled=true;
	if(document.frm.check1.checked==true){
		document.frm.submit.disabled=false;		
	}
	if(document.frm.check1.checked==false){
		document.frm.submit.enabled=false;
	}
}

